name: WDL CI
description: Test new/updated WDL tasks in a workflow repository by submitting to DNAstack Workbench
inputs:
  config-file:
    description: Config file
    required: false
    default: 'wdl-ci.config.json'
  wallet-url:
    description: Wallet URL
    required: true
    default: ${{ secrets.WALLET_URL }}
  wallet-client-id:
    description: Wallet Client ID
    required: true
    default: ${{ secrets.WALLET_CLIENT_ID }}
  wallet-client-secret:
    description: Wallet Client Secret
    required: true
    default: ${{ secrets.WALLET_CLIENT_SECRET }}
  workbench-namespace:
    description: Workbench Namespace
    required: true
    default: ${{ secrets.WORKBENCH_NAMESPACE }}
  workbench-ewes-url:
    description: Workbench EWES URL
    required: true
    default: ${{ secrets.WORKBENCH_EWES_URL }}
  workbench-workflow-service-url:
    description: Workbench Workflow Service URL
    required: true
    default: ${{ secrets.WORKBENCH_WORKFLOW_SERVICE_URL }}
  workbench-ewes-refresh-token:
    description: Workbench EWES Refresh Token
    required: true
    default: ${{ secrets.WORKBENCH_EWES_REFRESH_TOKEN }}
  workbench-workflow-service-refresh-token:
    description: Workbench Workflow Service Refresh Token
    required: true
    default: ${{ secrets.WORKBENCH_WORKFLOW_SERVICE_REFRESH_TOKEN }}
  wdl_ci_custom_test_wdl_dir:
    description: Directory to find custom test WDLs in
    required: false
runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: set-env
      shell: bash
      run: |
        echo "WALLET_URL=${{ inputs.wallet-url }}" >> $GITHUB_ENV
        echo "WALLET_CLIENT_ID=${{ inputs.wallet-client-id }}" >> $GITHUB_ENV
        echo "WALLET_CLIENT_SECRET=${{ inputs.wallet-client-secret }}" >> $GITHUB_ENV
        echo "WORKBENCH_NAMESPACE=${{ inputs.workbench-namespace }}" >> $GITHUB_ENV
        echo "WORKBENCH_EWES_URL=${{ inputs.workbench-ewes-url }}" >> $GITHUB_ENV
        echo "WORKBENCH_WORKFLOW_SERVICE_URL=${{ inputs.workbench-workflow-service-url }}" >> $GITHUB_ENV
        echo "WORKBENCH_EWES_REFRESH_TOKEN=${{ inputs.workbench-ewes-refresh-token }}" >> $GITHUB_ENV
        echo "WORKBENCH_WORKFLOW_SERVICE_REFRESH_TOKEN=${{ inputs.workbench-workflow-service-refresh-token }}" >> $GITHUB_ENV
        if [[ -n "${{ inputs.wdl_ci_custom_test_wdl_dir }}" ]]; then
          echo "WDL_CI_CUSTOM_TEST_WDL_DIR"=${{ inputs.wdl_ci_custom_test_wdl_dir }} >> $GITHUB_ENV
        fi
    - name: lint
      uses: docker://dnastack/wdl-ci:latest
      with:
        args: lint
    - name: detect-changes
      uses: docker://dnastack/wdl-ci:latest
      with:
        args: detect-changes
    - name: submit
      uses: docker://dnastack/wdl-ci:latest
      with:
        args: submit
    - name: monitor
      uses: docker://dnastack/wdl-ci:latest
      with:
        args: monitor --update-digests
      # If a test fails, still update task digests for any tests that succeeded
      # This allows fixing broken tests without rerunning successful runs
    - name: update-config
      if: always()
      uses: EndBug/add-and-commit@v9
      with:
        add: ${{ inputs.config-file }}
        message: "update wdl-ci config file after successful tests"
        default_author: github_actions
    - name: cleanup
      if: always()
      uses: docker://dnastack/wdl-ci:latest
      with:
        args: cleanup
