[project]
name = "wdl-testing-cli"
description = "DNAstack WDL testing CLI"
version = "0.1.0a0"
authors = [
    { name = "DNAstack", email = "devs@dnastack.com" }
]
dependencies = [
    "click",
    "dnastack-client-library",
    "jsonpickle",
    "miniwdl",
    "requests"
]

[project.scripts]
wdl-ci = "wdlci.cli.__main__:main"
